vim.api.nvim_set_hl(0, "LineNr", { fg = "#808080" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#B2A394", italic = true })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = nil })
vim.api.nvim_set_hl(0, "NvimTreeEndOfBuffer", { bg = nil, fg = nil })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { fg = "#c1c535", bg = "#202020" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#c1c535", bg = "#202020" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = nil })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = nil })
