vim.api.nvim_set_hl(0, "LineNr", { fg = "#707070" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#A29384", italic = true })
vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = nil })
vim.api.nvim_set_hl(0, "NvimTreeEndOfBuffer", { bg = nil })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#303030" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { bg = "#303030" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = nil })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = nil })
vim.api.nvim_set_hl(0, "@neorg.tags.ranged_verbatim.code_block", { bg = "#151515" })
