vim.api.nvim_set_hl(0, "Comment", { fg = "#A0A0A0" })
vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame", { fg = "#8080A0" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#9090B0" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = nil, fg = "#707090" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = nil })
vim.api.nvim_set_hl(0, "NvimTreeCursorLine", { bg = "#323742" })
vim.api.nvim_set_hl(0, "TelescopeSelection", { bg = "#323742" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = nil, fg = "#707090" })
vim.api.nvim_set_hl(0, "WinSeparator", { bg = nil, fg = "#404060" })
