require("functions")
require("keybindings")
require("options")
require("plugins-setup")
require("plugins.auto-session")
-- require("plugins.bufferline")
require("plugins.cmp")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.mason")
require("plugins.material")
-- require("plugins.material")
require("plugins.nvim-colorizer")
require("plugins.nvim-tree")
require("plugins.nvim-ufo")
require("plugins.smart-splits")
require("plugins.telescope")
require("plugins.toggle-lsp-diagnostics")
-- require("plugins.transparent")
require("plugins.treesitter")
require("plugins.vim-closetag")
require("plugins.which-key")
