# OSD.
w cycle-values osd-level 1 2 3
m show-progress

# Time.
j seek -3
l seek 3
Shift+l seek 1
Shift+j seek -1

# Volume.
Shift+i add volume 5
Shift+k add volume -5
v set volume 100

# Speed.
i add speed 0.25
k add speed -0.25
: add speed 0.25
; add speed -0.25
s set speed 1

# Playlist.
Ctrl+j playlist-prev ; set pause no
Ctrl+l playlist-next ; set pause no
