keep-open=always

osd-fractions=yes
osd-level=3
osd-status-msg="${filename} - ${time-pos/full} / ${duration/full} - (${percent-pos}%)"

osd-font-size=25

osd-align-x=left
osd-align-y=bottom

osd-bar-align-y=0.8
osd-bar-w=80
osd-bar-h=0.5
